# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in doctest2-rspec.gemspec
gemspec

gem "rake", "~> 13.0"

gem "rubocop", "~> 1.21"

# TODO: for temporary easy local development
gem 'doctest2-core', path: "../doctest2-core"
